### ISSUE TITLE
Base Boosting:  __init__() got an unexpected keyword argument 'stacking_layer'

### ISSUE THREAD

**Issue by helena9393** [a-wozniakowski/scikit-physlearn#50]
Hello, 

After installing the package, I tried to run the base boosting code <[https://scikit-physlearn.readthedocs.io/en/latest/baseboosting.html](url)>. However, I wasn't able to make an instance of the regressor object. Please see the attached screenshot, and let me know what I could do to resolve this issue. Thanks!
<img width="489" alt="Screen Shot 2021-07-14 at 11 24 06 AM" src="https://user-images.githubusercontent.com/66742776/125657816-129c10fd-3a23-4c37-9903-e243e60d58a6.png">

**Comment by a-wozniakowski** [comment]
Thank you for bringing attention to this issue. The example has been updated-- it replaces ``stacking_layer=stack`` with ``stacking_options=dict(layers=stack)``. The latter argument ``stacking_options`` allows the various options to be bundled into one argument.

To run the remaining portion of the example, please update to 0.1.7 which is the latest version. This version includes some nested cross-validation maintenance, as sklearn made some changes to the way they check scoring arguments.
