### ISSUE TITLE
Base Boosting Example: Scoring is invalid

### ISSUE THREAD

**Issue by helena9393** [a-wozniakowski/scikit-physlearn#53]
Hello, 

I tried to run the example in the base boosting docs again after changing the instantiation of the regressor, but now, the nested cross-validation procedure is not running to completion because of the scoring method. Please let me know what I could do to resolve this issue. I look forward to using this package!
<img width="816" alt="Screen Shot 2021-07-15 at 11 27 09 PM" src="https://user-images.githubusercontent.com/66742776/125891936-a3cd48f0-fb09-4bdf-bda0-a0ebcd6ae76e.png">

**Comment by a-wozniakowski** [comment]
Hi,

You'll need to update to version 0.1.7 which is available via [PyPI](https://pypi.org/project/scikit-physlearn/). This was mentioned in the earlier [issue](https://github.com/a-wozniakowski/scikit-physlearn/issues/50).

Notedly, the scoring issue stems from the following update to [sklearn](https://github.com/scikit-learn/scikit-learn/commit/9acfaab9667c038686ef51881adce72721ede377#diff-dfa830b15d3c3d544f99c5d022b7fb6067d97f3ff0289002291e78b65b02ec58), where ``_check_multimetric_scoring`` no longer accepts an ``str`` object as an argument.

**Comment by helena9393** [comment]
I do have the latest version, but the scoring issue still persists. Could you confirm that the Base Boosting example runs without errors? Thanks.

**Comment by a-wozniakowski** [comment]
I've run several tests without issue. 

Can you please try ``from physlearn import __version__``, then ``print(__version__)``, as well as ``from sklearn import __version__``, then ``print(__version__)``, and let me know the outcomes. Also, could you show the error message, so I can see at which line the error is occurring. The scoring is a ``str``, so it should never reach ``_check_multimetric_scoring`` to generate a ``ValueError``.
